### PR TITLE
question23 Leetcode added

### PR DESCRIPTION
**Pull request by aman34503**
_This is a template on how to fill out a PR properly._ 

## Description

- Language Used:  Python  		
- Approach Used: Merge Sort		
- Question(s) Solved: 1	
- Issue(s) related: https://github.com/DugarRishab/Algo.io/issues/22#issue-1393803343

 
## Acceptance Criteria

Screenshot from 2022-10-06 00-42-32

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by aman34503** [comment]
please accept the above PR under hacktoberfest-accepted n hacktober22 labels

**Comment by DugarRishab** [comment]
Hii @aman34503, can you please remove the previous commit.

**Comment by aman34503** [comment]
now its correct?

**Comment by DugarRishab** [comment]
Yes. Now it looks like it is correct. There is a problem with directory, because it was changed last night. Update you forked repo to bring it upto date with this repo.

**Pull request merged**
