### PR TITLE
Landing Page created in React website

### PR DESCRIPTION
**Pull request by Harikrishna3**
## Description
created in client page

Acceptance Criteria
Requirements
 Use React
 The design must be responsive
 Make the following directories inside /client/src/ :
 /components/ to store all components. Note: Each component should be in their respective folders inside '/compnents/`
 /pages/ to store all pages
 Route all the pages using routes.js file inside /client/src/.
 Create a template.md file in /client/src/ and write details about the color schema for future developers.
 Provide the full-screen screenshot of the final rendered page.

### CODE REVIEW

**Review by DugarRishab — APPROVED** [review]
`/src` should also be inside `/client`. All client related files should be inside `/client`. 
**Example directory:** 
- client
  - public
  - src
    - assests
    - components
    - other...
  - package.json
  - README.md
  - template.md

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Please do the requested changes.

**Comment by DugarRishab** [comment]
> `/src` should also be inside `/client`. All client related files should be inside `/client`. **Example directory:**
> 
> * client
>   
>   * public
>   * src
>     
>     * assests
>     * components
>     * other...
>   * package.json
>   * README.md
>   * template.md

This is how any react-app project should be structured

**Review by DugarRishab — APPROVED** [review]
LGTH

**Comment by Harikrishna3** [comment]
hacktoberfest accepted label 🙄

**Pull request merged**
