### PR TITLE
logo

### PR DESCRIPTION
**Pull request by 72002sweta**
_This is a template on how to fill out a PR properly._ 

## Description

- Language Used:  		
- Approach Used: 		
- Question(s) Solved:	
- Issue(s) related: 

 
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by DugarRishab** [comment]
Hi @72002sweta, I will be honest. The logo is really good. But I was hopping for something a little minimalistic. Something simple

**Comment by 72002sweta** [comment]
okay, I'll try to simplify it.

**Comment by 72002sweta** [comment]
made two more check it out

**Comment by DugarRishab** [comment]
To be honest, the initial one was much better. Okay, I will accepted this. 

Please remove all the new ones and just keep the initial ones, then I will accept it

**Comment by 72002sweta** [comment]
done

**Pull request merged**
