### PR TITLE
Added solution of Q102 of LeetCode

### PR DESCRIPTION
**Pull request by vivek-dhiman**
Binary Tree Level Order Traversal
Language used : C++
Data Structure used : Queue

### CODE REVIEW

**Comment by DugarRishab** [comment]
@vivek-dhiman Thanks for contributing. Please go through the description of the issue

**Comment by vivek-dhiman** [comment]
> @vivek-dhiman Thanks for contributing. Please go through the description of the issue

@DugarRishab Should I attach the test cases passed screenshot in the question's folder?

**Comment by DugarRishab** [comment]
> > @vivek-dhiman Thanks for contributing. Please go through the description of the issue
> 
> @DugarRishab Should I attach the test cases passed screenshot in the question's folder?

Yes. Please attach the screenshot.

**Comment by vivek-dhiman** [comment]
> > > @vivek-dhiman Thanks for contributing. Please go through the description of the issue
> > 
> > 
> > @DugarRishab Should I attach the test cases passed screenshot in the question's folder?
> 
> Yes. Please attach the screenshot.

@DugarRishab I have made the changes, please review and suggest any further changes or merge the request.

**Comment by DugarRishab** [comment]
@vivek-dhiman I have checked your screenshot. When I said Give a screenshot, I meant, give the screenshot as a comment or in the description of this pull request and not as a file in the repo. You can surely understand why an img cannot be pushed into the repo. Please check out other **closed** pull requests in this repo to understand what I mean

Anyway, The screenshot seems fine. Please delete the mentioned changes and I will merge this.

**Comment by DugarRishab** [comment]
Great code @vivek-dhiman. The explanation is a great touch. I will add this in the description so everyone does this like you. 

### Suggestion: 
The next time mention both the questions in the title and description of the Pull Request

**Pull request merged**
