### PR TITLE
Create  Q7_Reverse Integer.py

### PR DESCRIPTION
**Pull request by vatsal9117**
_This is a template on how to fill out a PR properly._ 

## Description
  reverse string

- Language Used: python	
- Approach Used: 		
- Question(s) Solved:Q7_Reverse Integer	
- Issue(s) related: Q7_Reverse Integer

 
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

image

### CODE REVIEW

**Comment by DugarRishab** [comment]
@vatsal9117 thanks for contributing.

**Comment by DugarRishab** [comment]
Can you please provide a screenshot as a proof of acceptance. Provide the said screenshot in the comments or description

**Comment by vatsal9117** [comment]
@DugarRishab i have uploaded screenshot

**Review by DugarRishab — APPROVED** [review]
Great !!

**Pull request merged**
