### PR TITLE
Q9_PalindromeNumber

### PR DESCRIPTION
**Pull request by napalion**
This is the solution for Question 9- Palindrome Number from LeetCode

- Language Used: Java 		
- Approach Used: look digit 		
- Question(s) Solved: Question 9 - Palindrome Number	
- Issue(s) Closes: Issue #12, but it is not closed yet.

This Question asked to verify if an int is Palindrome. Palindrome number is a number that reads the same backward as forward.

First of all, check if the number is negative(negative numbers can not be palindromes!).
This code copies the int given to make sure we don't lose it during the program. After that, we loop through the number and invert all the digits of the given x. At the end, we compare if the number given and the number made are the same, if they are: it means that the integer given is a palindrome(since it is read the same backward and forward), if they are not, the integer is no a palindrome.

 
## Acceptance Criteria

|     | Q1
|     | Q2
|     | Q3
|     | Q4
|     | Q5
|     | Q6
|     | Q7
|     | Q8
| ✓ | Q9
|     | Q10

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓| :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria
Screenshot from 2022-10-01 13-49-00

### CODE REVIEW

**Comment by DugarRishab** [comment]
Please provide the screenshot that clearly shows that your submission has passed all the tests. This screenshot just shows that your code just passes the 1st test.

**Comment by DugarRishab** [comment]
GREAT job with using the repo. Will use this as an example on how to properly submit a PR

**Comment by napalion** [comment]
> 
I totally took the wrong screenshot sorry!

image

**Comment by DugarRishab** [comment]
Great !!

**Review by DugarRishab — APPROVED** [review]

**Pull request merged**
