### PR TITLE
Added solution for Q1920 of Leetcode

### LINKED ISSUE #1: [Feature]: Add the solution of any LEET code
## Description: 
- Add the solution to any Leet Code question
- The solution must not already be present in this repo
- If submitting an alternative to any existing solution, please mark it as [Alternative]

## Eligibility Criteria: 
- [ ] The solution must pass all the tests on Leet code. Please provide a screenshot to prove the same
- [ ] If it is an alternative, then it must have a better time complexity than the previous solution.

### PR DESCRIPTION
**Pull request by anshrusia200**
_This is a template on how to fill out a PR properly._ 

## Description

- Language Used:  	CPP	
- Approach Used:   Initialized "ans" array with values as nums[nums[i]] using a for loop.		
- Question(s) Solved: 1920
- Issue(s) Closes: #1

 
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by DugarRishab** [comment]
Please provide a screenshot that clearly shows that this code has passed all tests on Leetcode

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Please provide the requested screenshot. Can you also explain a bit more about your approach?

**Comment by NiketBahety** [comment]
I want to review this PR can you please add me.

**Review by NiketBahety — APPROVED** [review]
Can you try to solve the follow up question also ?

**Comment by DugarRishab** [comment]
Merging this Pull Request because it was reviewed by @NiketBahety and accepted.

**Comment by anshrusia200** [comment]
Sure. Here is the screenshot
image

Approach : The array has elements within the range of valid indices of that array. We make a new array "ans" and initialize it with values such that value in nums array at that position works as index and the value at that index of nums is placed in corresponding index of "ans".

**Comment by anshrusia200** [comment]
I had one question. Why is this PR merge not considered by hacktoberfest. 
image

**Comment by anshrusia200** [comment]
> Can you try to solve the follow up question also ?

@NiketBahety Please specify question number.

**Comment by DugarRishab** [comment]
> I had one question. Why is this PR merge not considered by hacktoberfest. image

Check again. It should now be accepted

**Pull request merged**
