### PR TITLE
Added Leetcode Q.354 Russian Doll Envelopes

### PR DESCRIPTION
**Pull request by gaurang7goel**
[](url)The code is in the C++ (.cpp) language.
The concept of Dynamic Programming(DP) is used to solve it.
#1 Issue .
@DugarRishab please check.
The Screenshot for test cases is attached below 
Screenshot 2022-10-01 143434

### CODE REVIEW

**Comment by DugarRishab** [comment]
@gaurang7goel Please go through the README.md file to know how to make a proper Pull Request.

**Comment by gaurang7goel** [comment]
Ok sir.

**Comment by gaurang7goel** [comment]
Done Sir, please check once.

**Comment by DugarRishab** [comment]
Great !!! 
Thanks for contributing

**Comment by gaurang7goel** [comment]
Thank you.

**Pull request merged**
