### PR TITLE
Added solution of Q28

### PR DESCRIPTION
**Pull request by AryaDeepanshu**
## Description

- Language Used: Python3  		
- Approach Used: Python string library function
- Question(s) Solved: 28	
- Issue(s) related: 22

Python simply returns the the first index of occurence using .index()
image

 
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by AryaDeepanshu** [comment]
#22 
@DugarRishab , verify the PR.

**Comment by DugarRishab** [comment]
@AryaDeepanshu great work. 👍

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Please update the name of the files according to the given format

**Comment by AryaDeepanshu** [comment]
> Please update the name of the files according to the given format

done

**Review by DugarRishab — APPROVED** [review]

**Pull request merged**
