### PR TITLE
Added solution of 98. Validate Binary Search Tree of LeetCode

### PR DESCRIPTION
**Pull request by sarthak17jain**
Added the solution in C++ language.
image

Used recursion to solve Leetcode 98. Validate Binary Search Tree.

### CODE REVIEW

**Comment by DugarRishab** [comment]
Thanks, @sarthak17jain. Could you please provide a screenshot of the approval from the Leet Code. The screenshot must clearly show that your code passes all tests.

**Comment by sarthak17jain** [comment]
> Thanks, @sarthak17jain. Could you please provide a screenshot of the approval from the Leet Code. The screenshot must clearly show that your code passes all tests.

Added screenshot in orignal comment.

**Review by DugarRishab — APPROVED** [review]
Great !! But can you also add the header files in the future. Example: 
``` 
#include <bits/stdc++.h>
using namespace std;
```

**Comment by sarthak17jain** [comment]
> Great !! But can you also add the header files in the future. Example:
> 
> ```
> #include <bits/stdc++.h>
> using namespace std;
> ```

In leetcode it is not required since these are included in main.cpp while we write solution.cpp on leetcode.
On leetcode these are included by default.

**Pull request merged**
