### PR TITLE
Added solution of Question 34 of Leetcode (Find first and last position of an element in sorted array)

### PR DESCRIPTION
**Pull request by aman-netizen-ux**
Solution is in the JAVA language . It uses binary search.

### CODE REVIEW

**Comment by DugarRishab** [comment]
Great !! @aman-netizen-ux 
We needed variety in the language used. Can you please go through the description of issue #1.

**Comment by aman-netizen-ux** [comment]
Screenshot (439)

So sorry, I forgot to attach the screenshot in starting. Here, I'm attaching it.

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Can you please rename the file to fit the format? Example: 
``` 
Q2_2Sum.java
```

**Comment by aman-netizen-ux** [comment]
check now  whether is it okay or not ?

**Review by DugarRishab — APPROVED** [review]
Great !!

**Pull request merged**
