### PR TITLE
Add q41

### LINKED ISSUE #24: [FEATURE]: Add solution to Q41 to Q50 of Leetcode
# Description: 

- Add the solution of Q41 to Q50 of Leetcode in any language. 

# Questions: 

- [x] Q40 - cpp
- [x] Q41 - cpp
- [x] Q42 - cpp
- [x] Q43
- [x] Q44
- [x] Q45
- [x] Q46 - java
- [ ] Q47
- [x] Q48 - cpp
- [ ] Q49
- [x] Q50 - py

# Eligibility Criteria: 

- The solution must not already be there in this repo. If you want to add an alternative to any solution that is already present then mark it as `Alternative`
- The solution must pass all tests on Leetcode and do provide a screenshot proving the same. 
- NOTE: Get yourself assigned before sending a PR. PRs regarding this issue from non-assigned people will be marked `spam`

### PR DESCRIPTION
**Pull request by rakshitgondwal**
_This is a template on how to fill out a PR properly._ 

## Description

- Language Used:  	C++
- Approach Used: 	
Put each number in its right place.
For example:
When we find 5, then swap it with A[4].
At last, the first place where its number is not right, return the place + 1.	

- Question(s) Solved: 1	
- Issue(s) Closes:  #24 

 We only need to keep track of which ones of the first n positive integers occur in the array. To do this with no extra space, we can treat the array like a boolean array, where sign(arr[i]) indicates whether the i-th positive integer is present or not. First, we replace all non-positive values with n + 1, since we'll only use these indices as storage space. Then, for every one of the first n positive numbers in the array, we turn the value at their corresponding index negative. Finally, all we need to do is check for the first positive value, which will give us the first missing positive. If we find no such index, then all natural numbers up to n are present, so we return n + 1.

 
Screenshot (331)

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Review by DugarRishab — APPROVED** [review]
Please give the file an extension

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Give the file an extension

**Comment by rakshitgondwal** [comment]
> Give the file an extension

Done!

**Review by DugarRishab — APPROVED** [review]
GREAT !!

**Pull request merged**
