### PR TITLE
Added solution to question 50 of leetcode

### LINKED ISSUE #24: [FEATURE]: Add solution to Q41 to Q50 of Leetcode
# Description: 

- Add the solution of Q41 to Q50 of Leetcode in any language. 

# Questions: 

- [x] Q40 - cpp
- [x] Q41 - cpp
- [x] Q42 - cpp
- [x] Q43
- [x] Q44
- [x] Q45
- [x] Q46 - java
- [ ] Q47
- [x] Q48 - cpp
- [ ] Q49
- [x] Q50 - py

# Eligibility Criteria: 

- The solution must not already be there in this repo. If you want to add an alternative to any solution that is already present then mark it as `Alternative`
- The solution must pass all tests on Leetcode and do provide a screenshot proving the same. 
- NOTE: Get yourself assigned before sending a PR. PRs regarding this issue from non-assigned people will be marked `spam`

### PR DESCRIPTION
**Pull request by HeroKillerStain**
_This is a template on how to fill out a PR properly._ 

## Description

- Language Used:  	Python	
- Approach Used: 	Modular exponentiation
- Question(s) Solved: 1
- Issue(s) Closes: https://github.com/DugarRishab/Algo.io/issues/24

 This code takes an integer x and raises to it the power of n. It also takes into account negative power.
First we check if the power (i.e) is negative.If it is we make it positive and take a variable and set it to true. This will be used in the final step.For incrementing the power we check if the power is odd we multiply the result with the base number else we take the base number and multiply it by itself and also decrement the power by half. 
Finally we check if the neg variable is True.If it is we simply divide 1 by our answer.
solution accepted

 
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Please remove the screenshot from commit. Screenshot in description is enough

**Comment by HeroKillerStain** [comment]
Umm It doesn't show an option to delete the image in the commit section only the python file

**Comment by DugarRishab** [comment]
> Umm It doesn't show an option to delete the image in the commit section only the python file

You can make another commit to delete that image and that commit will automatically be added to this PR.

**Comment by HeroKillerStain** [comment]
no delete

**Comment by HeroKillerStain** [comment]
There is no option to delete this image
Only python file
python delete

**Comment by DugarRishab** [comment]
Okay. Leave it. I will do it myself

**Comment by DugarRishab** [comment]
From the next time do not add the image as a file in commit.

**Review by DugarRishab — APPROVED** [review]

**Comment by HeroKillerStain** [comment]
Thanks

**Pull request merged**
