### PR TITLE
Q31_Next Permutation

### PR DESCRIPTION
**Pull request by Sakshi2002-Sinha**
Link to the problem statement: https://leetcode.com/problems/next-permutation/ Leetcode: 31
Next permutation

_This is a template on how to fill out a PR properly._ 

## Description

- Language Used: Python 		
- Approach Used: Swap Sort	
- Question(s) Solved: 1
- Issue(s) related: 

I have added comments in the solution itself for complete understanding.
 
## Related Issue

Issues might come in observing the pattern,like how it is getting implemented.
## Acceptance Criteria

image

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|   * | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Review by DugarRishab — CHANGES_REQUESTED** [review]
Everything is great. But you have put the file in the wrong place

**Comment by DugarRishab** [comment]
The file should be in it's respective folder inside `/data/leetcode_solutions/`

**Comment by Sakshi2002-Sinha** [comment]
I have made the required changes. Kindly check it once.

**Review by DugarRishab — APPROVED** [review]
Okay. This LGTM

**Pull request merged**
